### ISSUE TITLE
Update Request: Bump to v2.5.0

### ISSUE THREAD

**Issue by Saijin-Naib** [flathub/ch.threema.threema-web-desktop#3]
https://github.com/threema-ch/threema-web/compare/v2.4.2...v2.5.0

There are a number of critical npm security updates/fixes and dependency bumps, as well as translation fixes, alongside a few connectivity/stability fixes that might improve UX for Threema Desktop when tethered to Threema Mobile.

(Thanks for having this Flatpak available, hugely helpful on my platform!)

**Comment by ljrk0** [comment]
Thanks for notifying me!  I'm sorry I couldn't reply earlier, I was busy working.  I've updated the build info in #4 and will merge as soon as the tests complete successfully.

Great to hear it's useful to you (running Silverblue?)!

**Comment by ljrk0** [comment]
Should be live now :)

**Comment by Saijin-Naib** [comment]
> Great to hear it's useful to you (running Silverblue?)!

Incredibly useful!

Alpine Linux, actually :)

**Comment by ljrk0** [comment]
Cool, wasn't actively aware Flatpak is used there but makes sense in retrospect.  Have fun and please just ping me again if you notice it's out of date, in *theory* I should get a notification but you know how it is :)

**Comment by Saijin-Naib** [comment]
Yeah, MUSL + OpenRC means AppImage and Snap are a no-go, but FlatPak works perfectly.

Will do! And thanks again! This is wonderful to have.
